In [1]:
import numpy as np
from prediction import simple_predict

In [2]:
x = np.arange(1,13).reshape((4,-1))

In [3]:
# Example 0:
theta1 = np.array([5, 0, 0, 0])
simple_predict(x, theta1)
# Ouput:
# array([5., 5., 5., 5.])
# Do you understand why y_hat contains only 5’s here?

array([5., 5., 5., 5.])

In [4]:
# Example 1:
theta2 = np.array([0, 1, 0, 0])
simple_predict(x, theta2)
# Output:
# array([ 1., 4., 7., 10.])
# Do you understand why y_hat == x[:,0] here?

array([ 1.,  4.,  7., 10.])

In [5]:
# Example 2:
theta3 = np.array([-1.5, 0.6, 2.3, 1.98])
simple_predict(x, theta3)
# Output:
# array([ 9.64, 24.28, 38.92, 53.56])

array([ 9.64, 24.28, 38.92, 53.56])

In [6]:
# Example 3:
theta4 = np.array([-3, 1, 2, 3.5])
simple_predict(x, theta4)
# Output:
# array([12.5, 32. , 51.5, 71. ])

array([12.5, 32. , 51.5, 71. ])