In [1]:
import numpy as np
from sigmoid import sigmoid_

In [3]:
# Example 1:
x = np.array(-4)
sigmoid_(x)
# Output:
# array([0.01798620996209156])

0.01798620996209156

In [4]:
# Example 2:
x = np.array(2)
sigmoid_(x)
# Output:
# array([0.8807970779778823])

0.8807970779778823

In [5]:
# Example 3:
x = np.array([[-4], [2], [0]])
sigmoid_(x)
# Output:
# array([[0.01798620996209156], [0.8807970779778823], [0.5]])

array([[0.01798621],
       [0.88079708],
       [0.5       ]])