In [10]:
import numpy as np
from mylinearregression import MyLinearRegression as MyLR

In [11]:
X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [34., 55., 89., 144.]])
Y = np.array([[23.], [48.], [218.]])
mylr = MyLR([[1.], [1.], [1.], [1.], [1]])

In [12]:
# Example 0:
Y_pred = mylr.predict_(X)
Y_pred
# Output:
# array([[8.], [48.], [323.]])

array([[  8.],
       [ 48.],
       [323.]])

In [13]:
# Example 1:
mylr.loss_elem_(Y, Y_pred)
# Output:
# array([[225.], [0.], [11025.]])

array([[  225.],
       [    0.],
       [11025.]])

In [16]:
# Example 2:
mylr.loss_(Y, Y_pred)
# Output:
# 1875.0

1875.0

In [17]:
# Example 3:
mylr.alpha = 1.6e-4
mylr.max_iter = 200000
mylr.fit_(X, Y)
mylr.thetas
# Output:
# array([[18.188..], [2.767..], [-0.374..], [1.392..], [0.017..]])

array([[ 1.81883792e+01],
       [ 2.76697788e+00],
       [-3.74782024e-01],
       [ 1.39219585e+00],
       [ 1.74138279e-02]])

In [22]:
# Example 4:
Y_pred = mylr.predict_(X)
Y_pred
# Output:
# array([[23.417..], [47.489..], [218.065...]])

array([[ 23.41720822],
       [ 47.48924883],
       [218.06563769]])

In [23]:
# Example 5:
mylr.loss_elem_(Y, Y_pred)
# Output:
# array([[0.174..], [0.260..], [0.004..]])

array([[0.1740627 ],
       [0.26086676],
       [0.00430831]])

In [24]:
# Example 6:
mylr.loss_(Y, Y_pred)
# Output:
# 0.0732..

0.07320629376956754