In [3]:
import numpy as np
from my_logistic_regression import MyLogisticRegression as MyLR


X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [3., 5., 9., 14.]])
Y = np.array([[1], [0], [1]])
mylr = MyLR([2, 0.5, 7.1, -4.3, 2.09])
# Example 0:
mylr.predict_(X)
# Output:
#array([[0.99930437],
#[1. ],
#[1. ]])


array([[0.99930437],
       [1.        ],
       [1.        ]])

In [4]:
# Example 1:
mylr.loss_(X,Y)
# Output:
#11.513157421577004


11.513157421577002

In [5]:
# Example 2:
mylr.fit_(X, Y)
mylr.thetas
# Output:
#array([[ 1.04565272],
#[ 0.62555148],
#[ 0.38387466],
#[ 0.15622435],
#[-0.45990099]])


array([[ 2.11826435],
       [ 0.10154334],
       [ 6.43942899],
       [-5.10817488],
       [ 0.6212541 ]])

In [6]:
# Example 3:
mylr.predict_(X)
# Output:
#array([[0.72865802],
#[0.40550072],
#[0.45241588]])


array([[0.57606717],
       [0.68599807],
       [0.06562156]])

In [7]:
# Example 4:
mylr.loss_(X,Y)
# Output:
#0.5432466580663214

1.4779126923052281