In [1]:
from data_spliter import data_spliter
import numpy as np

In [2]:
x1 = np.array([1, 42, 300, 10, 59])
y = np.array([0,1,0,1,0])

In [3]:
# Example 0:
data_spliter(x1, y, 0.8)
# Output:
# (array([ 10, 42, 1, 300]), array([59]), array([1, 1, 0, 0]), array([0]))

4


(array([[ 59],
        [  1],
        [300],
        [ 10]]),
 array([[42]]),
 array([0, 0, 0, 1]),
 array([1]))

In [4]:
# Example 1:
data_spliter(x1, y, 0.5)
# Output:
# (array([42, 10]), array([ 59, 300, 1]), array([1, 1]), array([0, 0, 0]))

2


(array([[ 10],
        [300]]),
 array([[ 1],
        [59],
        [42]]),
 array([1, 0]),
 array([0, 0, 1]))

In [5]:
x2 = np.array([ [ 1, 42],
[300, 10],
[ 59, 1],
[300, 59],
[ 10, 42]])
y = np.array([0,1,0,1,0])

In [6]:
# Example 2:
data_spliter(x2, y, 0.8)
# Output:
# (array([[ 10, 42],
# [ 59, 1],
# [ 1, 42],
# [300, 10]]), array([[300, 59]]), array([0, 0, 0, 1]),array([1]))

4


(array([[ 59,   1],
        [  1,  42],
        [ 10,  42],
        [300,  59]]),
 array([[300,  10]]),
 array([0, 0, 0, 1]),
 array([1]))

In [7]:
# Example 3:
data_spliter(x2, y, 0.5)
# Output:
# (array([[300, 10],
# [ 1, 42]]),
# array([[ 10, 42],
# [300, 59],
# [ 59, 1]]),
# array([1, 0]),
# array([0, 1, 0]))

2


(array([[300,  10],
        [300,  59]]),
 array([[10, 42],
        [ 1, 42],
        [59,  1]]),
 array([1, 1]),
 array([0, 0, 0]))