In [1]:
import numpy as np
from fit import fit_, predict_

In [2]:
x = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
y = np.array([[19.6], [-2.8], [-25.2], [-47.6]])
theta = np.array([[42.], [1.], [1.], [1.]])

In [3]:
# Example 0:
theta = fit_(x, y, theta, alpha = 0.0005, max_iter=42000)
theta
# Output:
# array([[41.99..],[0.97..], [0.77..], [-1.20..]])

array([[41.99888822],
       [ 0.97792316],
       [ 0.77923161],
       [-1.20768386]])

In [4]:
# Example 1:
predict_(x, theta)
# Output:
# array([[19.5992..], [-2.8003..], [-25.1999..], [-47.5996..]])

array([[ 19.59925884],
       [ -2.80037055],
       [-25.19999994],
       [-47.59962933]])